# Generated by Django 5.0.1 on 2024-02-06 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'gift',
                'verbose_name_plural': 'Gifts',
                'db_table': 'gifts',
            },
        ),
        migrations.CreateModel(
            name='GiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mnemo', models.CharField(db_index=True, max_length=10)),
            ],
            options={
                'verbose_name': 'gift type',
                'verbose_name_plural': 'Gift types',
                'db_table': 'gift_types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'products',
                'verbose_name_plural': 'Products',
                'db_table': 'product_models',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mnemo', models.CharField(db_index=True, max_length=10)),
            ],
            options={
                'verbose_name': 'product type',
                'verbose_name_plural': 'Product types',
                'db_table': 'product_types',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='GiftEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255)),
                ('qrcode', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gift')),
            ],
            options={
                'verbose_name': 'gift entry',
                'verbose_name_plural': 'Gift Entries',
                'db_table': 'gift_entries',
            },
        ),
        migrations.AddField(
            model_name='gift',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gifttype'),
        ),
        migrations.CreateModel(
            name='ProductEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'verbose_name': 'product entry',
                'verbose_name_plural': 'Product Entries',
                'db_table': 'product_entries',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producttype'),
        ),
    ]
